services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - jobify-app
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes: 
      - ./code/Database/schema/:/docker-entrypoint-initdb.d

  scraper:
    build: 
      context: ./code/Scraper
    environment:
      - DEPLOYMENT_ENV=compose
    ports:
      - 8000:8000
    networks:
      - jobify-app
    depends_on:
      - db
    expose:
      - 8000
networks:
  jobify-app: {}