services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - jobify-app
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "-u root", "-p$MYSQL_ROOT_PASSWORD",  "ping", "-h", "localhost"]
    ports:
      - "3306:3306"
    volumes: 
      - ./code/Database/schema/:/docker-entrypoint-initdb.d
  webapp:
    build:
      context: ./code/Web_app
    networks:
      - jobify-app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - 8080:80
  scraper:
    build: 
      context: ./code/Scraper
    environment:
      - DEPLOYMENT_ENV=compose
    ports:
      - 8000:8000
    networks:
      - jobify-app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    expose:
      - 8000
networks:
  jobify-app: {}