version: 2.1

orbs:
  python: circleci/python@1.2
  php: circleci/php@1.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: coverage run -m  pytest -q
      - run:
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

workflows:
  sample:
    jobs:
      - build-and-test
