---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jobify-scraper-parameters
  name: jobify-scraper-parameters
data: 
  parameters.json: | 
    {"server_name" : "jobify-db", "user_name":"root", "password": "root", "db_name": "srijas", "linked_in_pwd":"SRIJASGMAILPWD"}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobify-scraper
  name: jobify-scraper
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: jobify-scraper
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jobify-scraper
  name: jobify-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobify-scraper
  template:
    metadata:
      labels:
        app: jobify-scraper
    spec:
      containers:
        - env:
            - name: DEPLOYMENT_ENV
              value: "compose"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/ifjollancsu/jobify/jobify-scraper:latest
          imagePullPolicy: Always
          name: jobify-scraper
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /app/parameters.json
              subPath: parameters.json
              name: jobify-scraper-parameters
      volumes:
        - name: jobify-scraper-parameters
          configMap:
            name: jobify-scraper-parameters
---