apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobify-webapp
  name: jobify-webapp
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jobify-webapp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jobify-webapp
  name: jobify-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobify-webapp
  template:
    metadata:
      labels:
        app: jobify-webapp
    spec:
      containers:
        - env:
            - name: DEPLOYMENT_ENV
              value: "compose"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/ifjollancsu/jobify/jobify-webapp:latest
          imagePullPolicy: Always
          name: jobify-webapp
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html/parameters.json
              subPath: parameters.json
              name: jobify-webapp-parameters
      volumes:
        - name: jobify-webapp-parameters
          configMap:
            name: jobify-scraper-parameters
---