name: Running Code Coverage
on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.6.0
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.0
    - name: Install dependencies
      run: |
        pip install pytest-cov
        echo requirements installed
    - name: Run the tests
      run: |
          pip install -r requirements.txt
          pytest --cov=./

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
