on: push
name: Python Style Checker
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/pycodestyle-action@0.1.3
      - name: Flake8
        run: flake8 --ignore=E501,E402,E722
